export { default as BrainIcon } from "./brain-icon";
export { default as DiamondIcon } from "./diamond-icon";
export { default as EmailIcon } from "./email-icon";
export { default as FilterIcon } from "./filter-icon";
export { default as PenIcon } from "./pen-icon";
export { default as PersonIcon } from "./person-icon";
export { default as SoundIcon } from "./soundIcon";
export { default as TestIcon } from "./test-icon";
export { default as TorchIcon } from "./torch-icon";
